const acreditationList = document.querySelector("#acreditation-table tbody");
const cursesSelect = document.getElementById("cursesSelect");
let curseselected = "";
cursesSelect.addEventListener("change", function () {
  switch (cursesSelect.value) {
    case "110000":
      curseselected = "agro";
      cleanCursesTable();
      break;
    case "120000":
      curseselected = "basic";
      cleanCursesTable();

      break;
    case "130000":
      curseselected = "salud";
      cleanCursesTable();

      break;
    case "140000":
      curseselected = "constr";
      cleanCursesTable();

      break;
    case "150000":
      curseselected = "econom";
      cleanCursesTable();

      break;
    case "160000":
      curseselected = "hum";
      cleanCursesTable();

      break;
    case "170000":
      curseselected = "media";
      cleanCursesTable();

      break;
    case "180000":
      curseselected = "artes";
      cleanCursesTable();

      break;
    case "190000":
      curseselected = "ing";
      cleanCursesTable();

      break;
    case "200000":
      curseselected = "empre";
      cleanCursesTable();

      break;
    default:
      curseselected = "";
      cleanCursesTable();
  }
});
let centers = {
  agro: {
    id: 110000,
    name: "C. Agropecuarias",
  },
  basic: {
    id: 120000,
    name: "C. Básicas",
  },
  salud: {
    id: 130000,
    name: "C. de la Salud",
  },
  constr: {
    id: 140000,
    name: "C. del Diseño y Construcción",
  },
  econom: {
    id: 150000,
    name: "C. Economicas y Administrativas",
  },
  hum: {
    id: 160000,
    name: "C. Sociales y Humanitarias",
  },
  media: {
    id: 170000,
    name: "Educación Media",
  },
  artes: {
    id: 180000,
    name: "Artes y la Cultura",
  },
  ing: {
    id: 190000,
    name: "C. de la Ingeniería ",
  },
  empre: {
    id: 200000,
    name: "C. Empresariales",
  },
};
let curseInformation = [{
    center: centers["constr"],
    department: "Diseño de interiores",
    curseName: "Escalas del diseño interior",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Si",
    curseCredits: "3",
    act: "Si",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de interiores",
    curseName: "Construcción de terminología metodológica del diseño interior",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Si",
    curseCredits: "3",
    act: "Si",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["hum"],
    department: "Comunicación",
    curseName: "WireCast y streaming de contenido",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Si",
    curseCredits: "3",
    act: "Si",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["ing"],
    department: "Ingenieria Robotica",
    curseName: "Diseño de Técnicas de Control para Sistemas Neumáticos, Hidráulicos y Eléctricos",
    request: "Si",
    cursePlan: "No",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Economía",
    curseName: 'Herramientas Educativas Digitales "Microsoft Teams"',
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Economía",
    curseName: 'Herramientas Educativas Digitales "Aula Virtual UAA"',
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Economía",
    curseName: 'Herramientas Educativas Digitales "Apps educativas para el contexto digital"',
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Economía",
    curseName: "Uso de Series Desestacionalizados para el Análisis Económico",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Música",
    curseName: "Taller de producción radiofónica desde casa: Ventana al Sonido",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["media"],
    department: "Actividades Artísticas y Culturales",
    curseName: "Uso de Aula Virtual de la Plataforma Educativa Institucional Ámbito Académico en el Rol de Profesor",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "C. de la Computación",
    curseName: "Lenguaje de Java",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "C. de la Computación",
    curseName: "Uso de las TICs para Administración de un LMS",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["ing"],
    department: "Ingeniería Automotriz",
    curseName: "Procesos Básicos de Taller",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["hum"],
    department: "Comunicación",
    curseName: "Uso de WordPress para Creación de Páginas Web y Blogs Para Materias Prácticas de Comunicación",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["media"],
    department: "Actividades Deportivas",
    curseName: "Capacitación para el Uso y Manejo del Aula Virtual",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Estadística",
    curseName: "Herramientas Digitales para la Educación Virtual",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Estadística",
    curseName: "Herramientas Digitales en la Enseñanza de Probabilidad y Estadística",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Microbiología",
    curseName: "Herramientas Tecnológicas Básicas Orientadas a la Educación",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Fisiología y Farmacología",
    curseName: "Bioestadística Básica y Uso del programa Graph Pad Prism",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Fisiología y Farmacología",
    curseName: "Herramientas Tecnológicas en la Docencia Universtiaria",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Optometría",
    curseName: "Diseño Instruccional para las Asignaturas de la Licenciatura de Optometria",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Optometría",
    curseName: "Fisiología Clínica de la visión I",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Optometría",
    curseName: "Canalización de Pacientes",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Estadística",
    curseName: "Didáctica de la Estadística Básica",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Estadística",
    curseName: "Software Estadístico R como Apoyo a la Docencia",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Sistemas de la Información",
    curseName: "Introducción al Lenguaje de Programación Python",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Sistemas de Información",
    curseName: "Programación Web Básica",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Sistemas de Información",
    curseName: "Excel Avanzado",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["ing"],
    department: "Ingeniería Robótica",
    curseName: "Herramientas de Diseño en Ingeniería (AUTOCAD)",
    request: "sI",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "no",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["ing"],
    department: "Ingeniería Robótica",
    curseName: "Metodologías de Evaluación en los Aprendizajes Orientados a Proyectos de Ingeniería",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Fisiología y Farmacología",
    curseName: "Farmacología de los Antibióticos",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Ingeniería Bioquímica",
    curseName: "Proceso de Producción, Extracción, y Purificación de Aceite de la Cannabis",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Ingeniería Bioquímica",
    curseName: "Uso de Hongos en Biorremediación",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Ingeniería Bioquímica",
    curseName: "Herramientas para Aula Virtual y MS Teams en Ciencias Básicas y Ingenierías ",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Administración",
    curseName: "Coaching para Docentes",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Arte y Gestion Cultural",
    curseName: "Arte y Diversidad Sexual",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Arte y Gestion Cultural",
    curseName: "Taller de Diseño de Proyectos Culturales",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Arte y Gestion Cultural",
    curseName: "Iconografía Esóterica",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Arte y Gestion Cultural",
    curseName: "Como Hacer un Portafolio de Artista",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Arte y Gestión Cultural",
    curseName: "Arte y Misticismo de las Culturas Infígenas Rarámuri y Wixárika",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de Interiores",
    curseName: "Metodolgía del Diseño de Interiores: Acotación y Definición de las Escalas de Intervención del Proyecto de Diseño Interior",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de Interiores",
    curseName: "Escalas del Espacio Interior. 1 Parte: Definición de Conceptos y Escala del Diseño Interior",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de Interiores",
    curseName: "Escalas del Espacio Interior. 2 Parte: Definición de Conceptos y Escala del Diseño Interior",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Aclaramiento Dental",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Temas Selectos de Patología Bucal",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Rol Actual del Docente en el Ámbito Clinico",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Actualización en Prostodoncia Paricla Removible",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "La Docencia en Estomatología ante el Covid. Protocolos",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Manejo Estomatológico en Pacientes Sistémicos",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Anestesiología",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Introducción a la Clínica de Exodoncia",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Propedéutico de Operatoria Dental",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Técnicas Médico Quirúrgicas",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Estomatologia",
    curseName: "Fisiología de la Oclusión I",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["media"],
    department: "C. Sociales, Económicas e Historios",
    curseName: "Educando Conscientemente a Partir de mi Ser",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["media"],
    department: "C. Sociales, Económicas e Historios",
    curseName: "Taller de Adecuación de Materiales Didacticos al Aula Virtual",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["media"],
    department: "Actividades Deportivas",
    curseName: "Taller de Diseño de Experiencias de Aprendizaje y Elavoración de Material Propio",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Sistemas Electrónicos",
    curseName: "Introducción a Docker",
    request: "si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Sistemas Electrónicos",
    curseName: "Control de Versiones con Git",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de Moda",
    curseName: "Scrapboock. Cuaderno de bocetos para diseño de moda",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Gráfico",
    curseName: "Experiencia e interfaz de usuario en aplicaciones web y móviles",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Gráfico",
    curseName: "",
    request: "Si",
    cursePlan: "No",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Industrial",
    curseName: "Curso Básico de SolidWorks II",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Industrial",
    curseName: "Taller de Herramientas Digitales Apoyando la Docencia en la Carrera de Diseño Industrial",
    request: "Si",
    cursePlan: "No",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Urbano",
    curseName: "Transposición de Significados en el Proceso Creactivo de Diseño",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Ingeniería Civil",
    curseName: "Introducción a la Plataforma de Aula Virtual",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Ingeniería Civil",
    curseName: "Excel para Ingenieros",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Ingeniería Civil",
    curseName: "Herramientas Didácticas Complementarias para Plataformas Virtuales",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Ingeniería Civil",
    curseName: "Recursos en Línea y Software Open Source de Aplicación a la Docencia de la Ingeniería",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Ingeniería Civil",
    curseName: "Ambientes Virtuales para la Docencia en Ingeniería Civil",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de Moda",
    curseName: "Taller de Bordado con Técnicas Artesanales Mexicanas Modulo I",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de Moda",
    curseName: "Taller de Bordado con Técnicas Artesanales Mexicanas Modulo II",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de Moda",
    curseName: "Taller de Bordado con Técnicas Artesanales Mexicanas Modulo III",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Gráfico",
    curseName: "Análisis de las Tendencias Actuales en el Diseño Gráfico Modulo II",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Gráfico",
    curseName: "Técnicas de Recorte Papel",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Arquitectura",
    curseName: "Autocad 2D Architecture",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Arquitectura",
    curseName: "AutoCad 3D",
    request: "Si",
    cursePlan: "sI",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Arquitectura",
    curseName: "LUMION 8.5",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Industrial",
    curseName: "Aspectos Conceptuales y Didácticos en el Diseño de un Curso",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Arquitectura",
    curseName: "Enseñanza y Aprendizaje de la Arquitectura a Distancia",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Ingeniería Civil",
    curseName: "Introducción a la Plataforma Aula Virtual",
    request: "Si",
    cursePlan: "No",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Urbanismo",
    curseName: "Investigación Básica",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Urbanismo",
    curseName: "Curso Básico Excel",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Urbanismo",
    curseName: "Medición de Variables en Excel",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Arquitectura",
    curseName: "Revisión y Actualización de Programas de materias",
    request: "Si",
    cursePlan: "No",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño de Moda",
    curseName: "Diseño de Estampados",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["constr"],
    department: "Diseño Industrial",
    curseName: "Taller de Herramientas en Base de Datos Digitales Apoyando la Docencia en la Carrera de Diseño Industrial",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["empre"],
    department: "Agronegocios",
    curseName: "Excel para Docentes",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["empre"],
    department: "Agronegocios",
    curseName: "Metodología para la Publicación de Artículos Científicos",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Artes y la Cultura",
    curseName: "Taller de Diseño, Redacción y Evalaución de Proyectos Culturales",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Música",
    curseName: "Herramientas de Transmisión en Línea",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["basic"],
    department: "Microbiología",
    curseName: "Introducción a la Investigación Experimental: Redacción Cientifica",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Contabilidad",
    curseName: "Aspectos Generales de los sistemas de costos",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Contabilidad",
    curseName: "Crédito Bancario",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Contabilidad",
    curseName: "El Ejercicio Docente y la Contabilidad Gubernamental",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Contabilidad",
    curseName: "Normas de Información Financiera",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Economía",
    curseName: "Uso de series uniformes desestacionalizadas para el análisis económico",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Finanzas",
    curseName: "Análisis Financiero",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Finanzas",
    curseName: "Certificación Infosel",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },

  {
    center: centers["econom"],
    department: "Finanzas",
    curseName: "Estadística para Finanzas y Ciencias Económico Administrativas",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Finanzas",
    curseName: "Herramientas de Excel para el Modelaje Financiero",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Mercadotecnia",
    curseName: "Tropicalización de los Hábitos de Consumo, Sectores de Recuperación en la Nueva Normalidad",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Mercadotecnia",
    curseName: "Rebranding",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Recursos Humanos",
    curseName: "LMA: Lean Maturity Assessment como Instrumento de productividad de Clase Mundial",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Recursos Humanos",
    curseName: "Repensando el Genero",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Recursos Humanos",
    curseName: "Actualización en Tópicos de Calidad Industrial y Empresarial",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Recursos Humanos",
    curseName: "Como Detectar Mentiras en el Proceso de Selección de Recursos Humanos",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Recursos Humanos",
    curseName: "Los Recursos Humanos y el Nuevo Sistema Judicial Laboral",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Recursos Humanos",
    curseName: "Fundamentos Básicos de Sueldos y Salarios",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "",
    curseName: '"Maestria Personal" El Nuevo Perfil en los Recursos Humanos',
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Recursos Humanos",
    curseName: "Técnicas De Interpretación de Lenguaje Corporal",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Recursos Humanos",
    curseName: "Proceso de Mejora Continua en Organizaciones de Servicio",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Turismo",
    curseName: "Identidad con Sentido en las Organizaciones",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["econom"],
    department: "Finanzas",
    curseName: "Certificación INFOSEL",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["salud"],
    department: "Cultura física y salud pública",
    curseName: "Trabajo comunitario en salud pública",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
  {
    center: centers["artes"],
    department: "Artes Escénicas y Audiovisuales",
    curseName: "Procesos Producción Audiovisuales y Montajes",
    request: "No",
    cursePlan: "Si",
    participants: "Si",
    curseAutorization: "Por analizar",
    curseCredits: "-",
    act: "No",
    requestoToControl: "Pendiente",
    certificatoToDSCD: "Pendiente",
    certificateDevolution: "Pendiente",
    recordsGeneration: "Pendiente",
    recordsDelivered: "No",
  },
];
acreditationCurses();

function cursesOrdering() {
  return curseInformation.sort(function (a, b) {
    return a.center.id - b.center.id;
  });
}

function acreditationCurses() {
  for (let i = 0; i < cursesOrdering().length; i++) {
    if (
      curseselected !== "" &&
      curseInformation[i].center.name !== centers[curseselected].name
    ) {
      continue;
    }
    const row = document.createElement("tr");
    row.innerHTML = `
        <td class="center">${curseInformation[i].center.name}</td>
        <td class="department">${curseInformation[i].department}</td>
        <td class="curseName">${curseInformation[i].curseName}</td>
        <td class="request">${curseInformation[i].request}</td>
        <td class="cursePlan">${curseInformation[i].cursePlan}</td>
        <td class="participants">${curseInformation[i].participants}</td>
        <td class="curseAutorization">${curseInformation[i].curseAutorization}</td>
        <td class="curseCredits">${curseInformation[i].curseCredits}</td>
        <td class="act">${curseInformation[i].act}</td>
        <td class="requestoToControl">${curseInformation[i].requestoToControl}</td>
        <td class="certificatoToDSCD">${curseInformation[i].certificatoToDSCD}</td>
        <td class="certificateDevolution">${curseInformation[i].certificateDevolution}</td>
        <td class="recordsGeneration">${curseInformation[i].recordsGeneration}</td>
        <td class="recordsDelivered">${curseInformation[i].recordsDelivered}</td>
    `;
    acreditationList.appendChild(row);
  }
}

function cleanCursesTable() {
  while (acreditationList.firstChild) {
    acreditationList.removeChild(acreditationList.firstChild);
  }
  acreditationCurses();
}