const acreditationList = document.querySelector("#acreditation-table tbody");
const cursesSelect = document.getElementById("cursesSelect");
const keySelecter = document.getElementById("inlineCheckbox1");
const curseSelecter = document.getElementById("inlineCheckbox2");
const keySection = document.getElementById("keyContainer");
const curseSection = document.getElementById("curseContainer");
const key = document.getElementById("clave");
const wrapScroll = document.querySelector(".scrollTop");
const scrollDiv = document.querySelector(".scrollTopDiv");
const tableScroll = document.querySelector(".table-wrap");

const table_width = acreditationList.offsetWidth;
scrollDiv.setAttribute("style", "width:" + table_width + "px");
scrollDiv.style.width = table_width;


$(".scrollTop").scroll(function () {
  $(".table-wrap").scrollLeft($(".scrollTop").scrollLeft());
});
$(".table-wrap").scroll(function () {
  $(".scrollTop").scrollLeft($(".table-wrap").scrollLeft());
});


let initTopPosition = $('.table-wrap').offset().top;
setScrollHeight(initTopPosition);

let curseselected = "";
cursesSelect.addEventListener("change", function () {
  initTopPosition = $('.table-wrap').offset().top;
  setScrollHeight(initTopPosition);
  switch (cursesSelect.value) {
    case "110000":
      curseselected = "C Agropecuarias";
      cleanCursesTable();
      acreditationCurses();
      break;
    case "120000":
      curseselected = "C Básicas";
      cleanCursesTable();
      acreditationCurses();

      break;
    case "130000":
      curseselected = "C de la Salud";
      cleanCursesTable();
      acreditationCurses();

      break;
    case "140000":
      curseselected = "C del Diseño y de la C";
      cleanCursesTable();
      acreditationCurses();

      break;
    case "150000":
      curseselected = "C de C Económicas y A";
      cleanCursesTable();
      acreditationCurses();

      break;
    case "160000":
      curseselected = "C Sociales y humanidades";
      cleanCursesTable();
      acreditationCurses();

      break;
    case "170000":
      curseselected = "C. de Educación Media";
      cleanCursesTable();
      acreditationCurses();

      break;
    case "180000":
      curseselected = "C del Arte y de la Cultura";
      cleanCursesTable();
      acreditationCurses();

      break;
    case "190000":
      curseselected = "C de la Ingeniería";
      cleanCursesTable();
      acreditationCurses();

      break;
    case "200000":
      curseselected = "C de C Empresariales";
      cleanCursesTable();
      acreditationCurses();

      break;
    default:
      curseselected = "";
      cleanCursesTable();
      acreditationCurses();
  }
});

keySelecter.addEventListener("change", function () {
  initTopPosition = $('.table-wrap').offset().top;
  setScrollHeight(initTopPosition);
  if (this.checked) {
    document.getElementById("inlineCheckbox2").disabled = true;
    keySection.classList.remove("not-shown");
  } else {
    keySection.classList.add("not-shown");
    document.getElementById("inlineCheckbox2").disabled = false;
    key.value = "";
    cleanCursesTable();
    acreditationCurses();

  }
});

key.addEventListener("input", function (e) {
  filterKey(key.value);
});

curseSelecter.addEventListener("change", function () {
  initTopPosition = $('.table-wrap').offset().top;
  setScrollHeight(initTopPosition);
  if (this.checked) {
    document.getElementById("inlineCheckbox1").disabled = true;
    curseSection.classList.remove("not-shown");
  } else {
    curseSection.classList.add("not-shown");
    document.getElementById("inlineCheckbox1").disabled = false;
    curseselected = "";
    cleanCursesTable();
    acreditationCurses();
  }
});
let centers = {
  dgdp: {
    id: 6,
    name: "DGDP",
  },
  agro: {
    id: 11,
    name: "C. Agropecuarias",
  },
  basic: {
    id: 12,
    name: "C. Básicas",
  },
  salud: {
    id: 13,
    name: "C. de la Salud",
  },
  constr: {
    id: 14,
    name: "C. del Diseño y Construcción",
  },
  econom: {
    id: 15,
    name: "C. Economicas y Administrativas",
  },
  hum: {
    id: 16,
    name: "C. Sociales y Humanitarias",
  },
  media: {
    id: 17,
    name: "Educación Media",
  },
  artes: {
    id: 18,
    name: "Artes y la Cultura",
  },
  ing: {
    id: 19,
    name: "C. de la Ingeniería ",
  },
  empre: {
    id: 20,
    name: "C. Empresariales",
  },
};

let departments = {
  4: {
    name: "Desarrollo Curricular",
    id: "4",
    center: "6",
  },
  5: {
    name: "Innovación Educativa",
    id: "5",
    center: "6",
  },
  1105: {
    name: "C. de los Alimentos",
    id: "1105",
    center: "11",
  },
  1107: {
    name: "C. Agronómicas",
    id: "1107",
    center: "11",
  },
  1108: {
    name: "C. Veterinarias",
    id: "1108",
    center: "11",
  },
  1201: {
    name: "Biología",
    id: "1201",
    center: "12",
  },
  1202: {
    name: "Estadística",
    id: "1202",
    center: "12",
  },
  1203: {
    name: "Fisiología y Farmacología",
    id: "1203",
    center: "12",
  },
  1204: {
    name: "Ing. Bioquímica",
    id: "1204",
    center: "12",
  },
  1205: {
    name: "Matemáticas y Física",
    id: "1205",
    center: "12",
  },
  1206: {
    name: "Microbiología",
    id: "1206",
    center: "12",
  },
  1207: {
    name: "Morfología",
    id: "1207",
    center: "12",
  },
  1208: {
    name: "Química",
    id: "1208",
    center: "12",
  },
  1209: {
    name: "Sistemas de Información",
    id: "1209",
    center: "12",
  },
  1210: {
    name: "Sistemas Electrónicos",
    id: "1210",
    center: "12",
  },
  1211: {
    name: "Ciencias de la Computación",
    id: "1211",
    center: "12",
  },
  1302: {
    name: "Enfermería",
    id: "1302",
    center: "13",
  },
  1303: {
    name: "Estomatología",
    id: "1303",
    center: "13",
  },
  1304: {
    name: "Medicina",
    id: "1304",
    center: "13",
  },
  1305: {
    name: "Optometría",
    id: "1305",
    center: "13",
  },
  1309: {
    name: "Cultura Física y Salud Pública",
    id: "1309",
    center: "13",
  },
  1310: {
    name: "Nutrición",
    id: "1310",
    center: "13",
  },
  1311: {
    name: "Terapia física",
    id: "1311",
    center: "13",
  },
  1403: {
    name: "Diseño Industrial",
    id: "1403",
    center: "14",
  },
  1405: {
    name: "Diseño de Moda",
    id: "1405",
    center: "14",
  },
  1406: {
    name: "Diseño Gráfico",
    id: "1406",
    center: "14",
  },
  1407: {
    name: "Urbanismo",
    id: "1407",
    center: "14",
  },
  1408: {
    name: "Arquitectura",
    id: "1408",
    center: "14",
  },
  1409: {
    name: "Diseño de Interiores",
    id: "1409",
    center: "14",
  },
  1410: {
    name: "Ingeniería Civil",
    id: "1410",
    center: "14",
  },
  1501: {
    name: "Administración",
    id: "1501",
    center: "15",
  },
  1502: {
    name: "Contaduría",
    id: "1502",
    center: "15",
  },
  1503: {
    name: "Economía",
    id: "1503",
    center: "15",
  },
  1504: {
    name: "Finanzas",
    id: "1504",
    center: "15",
  },
  1505: {
    name: "Mercadotecnia",
    id: "1505",
    center: "15",
  },
  1506: {
    name: "Recursos Humanos",
    id: "1506",
    center: "15",
  },
  1507: {
    name: "Turismo",
    id: "1507",
    center: "15",
  },
  1601: {
    name: "Comunicación",
    id: "1601",
    center: "16",
  },
  1602: {
    name: "Derecho",
    id: "1602",
    center: "16",
  },
  1603: {
    name: "Educación",
    id: "1603",
    center: "16",
  },
  1604: {
    name: "Filosofía",
    id: "1604",
    center: "16",
  },
  1605: {
    name: "Historia",
    id: "1605",
    center: "16",
  },
  1606: {
    name: "Idiomas",
    id: "1606",
    center: "16",
  },
  1608: {
    name: "Psicología",
    id: "1608",
    center: "16",
  },
  1609: {
    name: "Sociología y Antropología",
    id: "1609",
    center: "16",
  },
  1610: {
    name: "Trabajo Social",
    id: "1610",
    center: "16",
  },
  1611: {
    name: "Ciencias Políticas",
    id: "1611",
    center: "16",
  },
  1701: {
    name: "Actividades Artisticas y Culturales",
    id: "1701",
    center: "17",
  },
  1702: {
    name: "Actividades Deportivas",
    id: "1702",
    center: "17",
  },
  1704: {
    name: "Ciencias Sociales,Economicas e Historia",
    id: "1704",
    center: "17",
  },
  1705: {
    name: "Filosofía y letras",
    id: "1705",
    center: "17",
  },
  1707: {
    name: "Idiomas",
    id: "1707",
    center: "17",
  },
  1708: {
    name: "Matemáticas y Física",
    id: "1708",
    center: "17",
  },
  1709: {
    name: "Ciencias QuÍmico-BiolÓgicas",
    id: "1709",
    center: "17",
  },
  1801: {
    name: "Arte y Gestión Cultural",
    id: "1801",
    center: "18",
  },
  1802: {
    name: "Letras",
    id: "1802",
    center: "18",
  },
  1803: {
    name: "Música",
    id: "1803",
    center: "18",
  },
  1805: {
    name: "Artes Escenicas y Audiovisuales",
    id: "1805",
    center: "18",
  },
  1902: {
    name: "Ingeniería Automotriz",
    id: "1902",
    center: "19",
  },
  1903: {
    name: "Ingeniería Robótica",
    id: "1903",
    center: "19",
  },
  1904: {
    name: "Ingeniería Biomédica",
    id: "1904",
    center: "19",
  },
  2002: {
    name: "Agronegocios",
    id: "2002",
    center: "20",
  },
  2003: {
    name: "Comercio electrónico",
    id: "2003",
    center: "20",
  },
};
let curseInformation = [{
    number: "1",
    curseName: "Metodología institucional para el diseño curricular",
    curseKey: "-",
    controlKey: "-",
    centerKey: "6",
    center: "DGDP",
    departmentKey: "4",
    department: "Desarrollo Curricular",
    receptionDate: "1/15/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "35",
    curseCredits: "4",
    curseStart: "3/4/19",
    curseEnd: "6/14/19",
    autorization: "1/16/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "N/A",
  },
  {
    number: "2",
    curseName: "Manejo seguro de sustancias químicas peligrosas",
    curseKey: "-",
    controlKey: "-",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1201",
    department: "Bilogía",
    receptionDate: "7/15/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "1",
    curseStart: "7/20/20",
    curseEnd: "8/7/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "3",
    curseName: "Didáctica de la Estadística Básica",
    curseKey: "8648",
    controlKey: "20265",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1202",
    department: "Estadística",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "23",
    curseCredits: "2",
    curseStart: "7/20/20",
    curseEnd: "8/7/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "4",
    curseName: "Herramientas digitales en la enseñanza de Probabilidad y Estadística",
    curseKey: "8650",
    controlKey: "20269",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1202",
    department: "Estadística",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "21",
    curseCredits: "1",
    curseStart: "7/8/20",
    curseEnd: "7/17/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "8/11/20",
    teachersCapture: "8/11/20",
  },
  {
    number: "5",
    curseName: "Herramientas digitales para la educación virtual",
    curseKey: "8649",
    controlKey: "20266",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1202",
    department: "Estadística",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "23",
    curseCredits: "1",
    curseStart: "7/8/20",
    curseEnd: "7/17/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "6",
    curseName: "Software estadístico R como apoyo a la docencia",
    curseKey: "8651",
    controlKey: "20270",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1202",
    department: "Estadística",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "23",
    curseCredits: "2",
    curseStart: "8/3/20",
    curseEnd: "8/21/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "7",
    curseName: "Bioestadística básica y uso del programa Graph Pad Prism",
    curseKey: "8652",
    controlKey: "20271",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1203",
    department: "Fisiología y F",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "11",
    curseCredits: "1",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "8",
    curseName: "Farmacología de los antibióticos",
    curseKey: "8653",
    controlKey: "20272",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1203",
    department: "Fisiología y F",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "10",
    curseCredits: "2",
    curseStart: "8/3/20",
    curseEnd: "8/23/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "9",
    curseName: "Herramientas tecnológicas en la docencia universitaria",
    curseKey: "8654",
    controlKey: "20273",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1203",
    department: "Fisiología y F",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "11",
    curseCredits: "4",
    curseStart: "7/6/20",
    curseEnd: "8/20/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "10",
    curseName: "Herramientas para aula virtual y MS Teams en C Básicas e Ingenierías",
    curseKey: "8655",
    controlKey: "20274",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1204",
    department: "Ing Bioquímica",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "16",
    curseCredits: "4",
    curseStart: "7/6/20",
    curseEnd: "8/14/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "11",
    curseName: "Proceso de producción, extracción y purificación de aceite de cannabis",
    curseKey: "8657",
    controlKey: "20275",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1204",
    department: "Ing Bioquímica",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "9",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "8/14/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "12",
    curseName: "Uso de hongos en Biorremediación",
    curseKey: "8658",
    controlKey: "20276",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1204",
    department: "Ing Bioquímica",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "11",
    curseCredits: "4",
    curseStart: "7/6/20",
    curseEnd: "8/14/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "13",
    curseName: "Elaboración de reactivos para Álgebra y Álgebra lineal con Wiris",
    curseKey: "8659",
    controlKey: "20277",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1205",
    department: "Matemáticas",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "39",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "14",
    curseName: "Elaboración de reactivos para Cálculo Diferencial con Wiris",
    curseKey: "8660",
    controlKey: "20278",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1205",
    department: "Matemáticas",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "45",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "15",
    curseName: "Elaboración de reactivos para Cálculo Integral con Wiris",
    curseKey: "8661",
    controlKey: "20281",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1205",
    department: "Matemáticas",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "40",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "16",
    curseName: "Elaboración de reactivos para ecuaciones diferenciales con Wiris",
    curseKey: "8662",
    controlKey: "20280",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1205",
    department: "Matemáticas",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "40",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "17",
    curseName: "Reactivos de opción múltiple con Wiris",
    curseKey: "8478",
    controlKey: "19829",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1205",
    department: "Matemáticas",
    receptionDate: "12/13/19",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "13",
    curseCredits: "4",
    curseStart: "1/1/20",
    curseEnd: "1/28/20",
    autorization: "1/13/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "1/13/20",
  },
  {
    number: "18",
    curseName: "Seminario de matemáticas aplicadas 2020",
    curseKey: "6998",
    controlKey: "19839",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1205",
    department: "Matemáticas",
    receptionDate: "1/30/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "7",
    curseCredits: "3",
    curseStart: "1/31/20",
    curseEnd: "5/29/20",
    autorization: "2/7/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "2/7/20",
  },
  {
    number: "19",
    curseName: "Actualización en materia de normatividad aplicable a laboratorios clínicos y farmacias",
    curseKey: "8480",
    controlKey: "19830",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1206",
    department: "Microbiología",
    receptionDate: "12/13/19",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "20",
    curseCredits: "1",
    curseStart: "1/13/20",
    curseEnd: "1/17/20",
    autorization: "1/13/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "1/13/20",
  },
  {
    number: "20",
    curseName: "Herramientas tecnológicas orientadas a la educación",
    curseKey: "8663",
    controlKey: "20282",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1206",
    department: "Microbiología",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "18",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "8/10/20",
    teachersCapture: "-",
  },
  {
    number: "21",
    curseName: "Introducción a la investigación experimental: Redacción científica",
    curseKey: "8664",
    controlKey: "20283",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1206",
    department: "Microbiología",
    receptionDate: "7/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Alumnos",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "Cancelado",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "22",
    curseName: "Excel avanzado",
    curseKey: "8665",
    controlKey: "20284",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1209",
    department: "Sist. De Información",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "11",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "23",
    curseName: "Introducción al lenguaje de programación Python",
    curseKey: "8666",
    controlKey: "20285",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1209",
    department: "Sist. De Información",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "16",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "24",
    curseName: "Programación web básica",
    curseKey: "8667",
    controlKey: "20286",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1209",
    department: "Sist. De Información",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "20",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "25",
    curseName: "Control de versiones con Git",
    curseKey: "8668",
    controlKey: "20287",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1210",
    department: "Sist. Electrónicos",
    receptionDate: "7/10/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "14",
    curseCredits: "3",
    curseStart: "7/13/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "26",
    curseName: "Introducción a Docker",
    curseKey: "8670",
    controlKey: "20288",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1210",
    department: "Sist. Electrónicos",
    receptionDate: "7/10/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "3",
    curseStart: "7/13/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "27",
    curseName: "Introducción a MongoDB",
    curseKey: "8671",
    controlKey: "20289",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1210",
    department: "Sist. Electrónicos",
    receptionDate: "7/10/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "14",
    curseCredits: "3",
    curseStart: "8/3/20",
    curseEnd: "8/23/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "28",
    curseName: "Microcontrolador ATMega8515",
    curseKey: "8672",
    controlKey: "20290",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1210",
    department: "Sist. Electrónicos",
    receptionDate: "7/10/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "3",
    curseStart: "8/3/20",
    curseEnd: "8/23/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "29",
    curseName: "Lenguaje de Java",
    curseKey: "8673",
    controlKey: "20291",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1211",
    department: "C de la Computación",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "10",
    curseCredits: "4",
    curseStart: "7/6/20",
    curseEnd: "8/21/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "30",
    curseName: "Uso de TIC's para administración de LMS",
    curseKey: "8674",
    controlKey: "20292",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1211",
    department: "C de la Computación",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "20",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "8/21/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "31",
    curseName: "IX Seminario Académico Clínico en Optometría",
    curseKey: "N/A",
    controlKey: "N/A",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1305",
    department: "Optometría",
    receptionDate: "1/22/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "20",
    curseCredits: "2",
    curseStart: "1/31/20",
    curseEnd: "6/6/20",
    autorization: "1/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "N/A",
  },
  {
    number: "32",
    curseName: "Cátedra Alfonso Pérez Romo",
    curseKey: "N/A",
    controlKey: "N/A",
    centerKey: "18",
    center: "De las Artes y la Cultura",
    departmentKey: "1801",
    department: "Arte y gestión cultural",
    receptionDate: "12/13/19",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "2",
    curseCredits: "1",
    curseStart: "10/15/19",
    curseEnd: "10/18/19",
    autorization: "1/8/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "N/A",
  },
  {
    number: "33",
    curseName: "Aspectos Pedagógicos del Docente de Enfermerá en Ed Superior",
    curseKey: "8675",
    controlKey: "20293",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1302",
    department: "Enfermería",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "17",
    curseCredits: "4",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "34",
    curseName: "Reactivos para el EGEL-ENFER",
    curseKey: "8676",
    controlKey: "20294",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1302",
    department: "Enfermería",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "26",
    curseCredits: "1",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "35",
    curseName: "Acttualización en Prostodoncia parcial removible",
    curseKey: "8677",
    controlKey: "20295",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1303",
    department: "Estomatología",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "4",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "36",
    curseName: 'La docencia en Estomatología ante CIVID "Protocolos"',
    curseKey: "8678",
    controlKey: "20296",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1303",
    department: "Estomatología",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "4",
    curseCredits: "2",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "37",
    curseName: "Manejo Estomatológico en paciente sistémico",
    curseKey: "8679",
    controlKey: "20297",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1303",
    department: "Estomatología",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "11",
    curseCredits: "2",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "38",
    curseName: "Aclaramiento dental",
    curseKey: "8680",
    controlKey: "20298",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1303",
    department: "Estomatología",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "5",
    curseCredits: "3",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "39",
    curseName: "Rol actual docente en el ámbito clínico",
    curseKey: "8681",
    controlKey: "20299",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1303",
    department: "Estomatología",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "6",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "40",
    curseName: "Fisiología Clínica de la Visión I",
    curseKey: "8682",
    controlKey: "20300",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1305",
    department: "Optometría",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "19",
    curseCredits: "2",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "41",
    curseName: "Trabajo Comunitario en Salud Pública",
    curseKey: "8683",
    controlKey: "20301",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1310",
    department: "Cultura Física y Salud Pública",
    receptionDate: "7/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "8",
    curseCredits: "2",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/23/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "42",
    curseName: "Aspectos conceptuales y didácticos en el diseño de un curso (grupo 1 y2)",
    curseKey: "8684",
    controlKey: "20302",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1403",
    department: "Diseño Industrial",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "4",
    curseStart: "7/10/20",
    curseEnd: "8/21/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "43",
    curseName: "Cuso básico de solid works II",
    curseKey: "8685",
    controlKey: "20303",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1403",
    department: "Diseño Industrial",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "3",
    curseStart: "7/1/20",
    curseEnd: "7/31/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "44",
    curseName: "Taller de herramientas digitales apoyando la docencia en Diseño Industrial",
    curseKey: "8686",
    controlKey: "20304",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1403",
    department: "Diseño Industrial",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "10",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/26/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "45",
    curseName: "Diseño de estampados",
    curseKey: "8687",
    controlKey: "20305",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1405",
    department: "Diseño de Moda",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "18",
    curseCredits: "6",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "46",
    curseName: "Scrapbook: Cuaderno de bocetos para diseño de moda",
    curseKey: "8688",
    controlKey: "20306",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1405",
    department: "Diseño de Moda",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "No",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "Cancelado",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "47",
    curseName: "Taller de bordado con técnicas artesanales mexicanas, Módulo I, II y III (sostenibilidad de la técnica)",
    curseKey: "8689",
    controlKey: "20307",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1405",
    department: "Diseño de Moda",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "29",
    curseCredits: "6",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "48",
    curseName: "Experiencia e interfaz de usuario en aplicaciones web móviles",
    curseKey: "8690",
    controlKey: "20308",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1406",
    department: "Diseño Gráfico",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "15",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/26/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "49",
    curseName: "Técnicas de recorte de papel",
    curseKey: "8691",
    controlKey: "26309",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1406",
    department: "Diseño Gráfico",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "26",
    curseCredits: "5",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "50",
    curseName: "Curso básico de Excel",
    curseKey: "8692",
    controlKey: "20310",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1407",
    department: "Urbanismo",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "17",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "8/17/20",
    teachersCapture: "8/17/20",
  },
  {
    number: "51",
    curseName: "Investigación básica",
    curseKey: "8693",
    controlKey: "20311",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1407",
    department: "Urbanismo",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "52",
    curseName: "Medición de variables en Excel",
    curseKey: "8694",
    controlKey: "20312",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1407",
    department: "Urbanismo",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "8",
    curseCredits: "2",
    curseStart: "7/27/20",
    curseEnd: "8/14/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "8/17/20",
    teachersCapture: "8/17/20",
  },
  {
    number: "62",
    curseName: "Introducción a la plataforma de aula Virtual",
    curseKey: "8703",
    controlKey: "20321",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1410",
    department: "Ingeniería Civil",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "22",
    curseCredits: "1",
    curseStart: "7/6/20",
    curseEnd: "7/23/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "8/17/20",
    teachersCapture: "8/17/20",
  },
  {
    number: "63",
    curseName: "Recursos en línea y software open source de aplicación a la docencia de la ingeniería",
    curseKey: "8704",
    controlKey: "20322",
    centerKey: "14",
    center: "C del Diseño y de la C",
    departmentKey: "1410",
    department: "Ingeniería Civil",
    receptionDate: "7/9/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "64",
    curseName: "Coaching para docentes",
    curseKey: "8705",
    controlKey: "20323",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1501",
    department: "Administración",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "27",
    curseCredits: "2",
    curseStart: "7/13/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "8/17/20",
    teachersCapture: "8/17/20",
  },
  {
    number: "65",
    curseName: "Aspectos generales de los sistemas de costos",
    curseKey: "8706",
    controlKey: "20324",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1502",
    department: "Contaduría",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "33",
    curseCredits: "1",
    curseStart: "7/13/20",
    curseEnd: "7/17/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "66",
    curseName: "Crédito bancario",
    curseKey: "8707",
    controlKey: "20325",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1502",
    department: "Contaduría",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "67",
    curseName: "El ejercicio docente y la contabilidad gubrnamental",
    curseKey: "8708",
    controlKey: "20326",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1502",
    department: "Contaduría",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "24",
    curseCredits: "3",
    curseStart: "7/13/20",
    curseEnd: "7/17/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "68",
    curseName: "Normas de información financiera",
    curseKey: "8709",
    controlKey: "20327",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1502",
    department: "Contaduría",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "29",
    curseCredits: "1",
    curseStart: "7/6/20",
    curseEnd: "7/10/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "69",
    curseName: "Apps educativas para el contexto digital",
    curseKey: "8710",
    controlKey: "20328",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1503",
    department: "Economía",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "23",
    curseCredits: "3",
    curseStart: "8/10/20",
    curseEnd: "8/21/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "70",
    curseName: "Herramientas Educativas Digitales",
    curseKey: "8711",
    controlKey: "20329",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1503",
    department: "Economía",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "23",
    curseCredits: "3",
    curseStart: "7/27/20",
    curseEnd: "8/7/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "71",
    curseName: "Microsoft Teams",
    curseKey: "8712",
    controlKey: "20330",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1503",
    department: "Economía",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "30",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "8/10/20",
    teachersCapture: "8/11/20",
  },
  {
    number: "72",
    curseName: "Uso de series uniformes desestacionalizadas para el análisis económico",
    curseKey: "8713",
    controlKey: "20331",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1503",
    department: "Economía",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "14",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "8/21/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "73",
    curseName: "Análisis financiero",
    curseKey: "8714",
    controlKey: "20332",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1504",
    department: "Finanzas",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "9",
    curseCredits: "1",
    curseStart: "7/13/20",
    curseEnd: "7/17/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "74",
    curseName: "Certificación infosel",
    curseKey: "8715",
    controlKey: "20333",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1504",
    department: "Finanzas",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "15",
    curseCredits: "1",
    curseStart: "7/13/20",
    curseEnd: "7/17/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "75",
    curseName: "Estadística para finanzas y Ciencias Económico Administrativas",
    curseKey: "8716",
    controlKey: "20334",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1504",
    department: "Finanzas",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "18",
    curseCredits: "1",
    curseStart: "1/1/20",
    curseEnd: "6/30/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "76",
    curseName: "Herramientas de Excel para el modelaje financiero",
    curseKey: "8717",
    controlKey: "20335",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1504",
    department: "Finanzas",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "13",
    curseCredits: "1",
    curseStart: "1/1/20",
    curseEnd: "6/30/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "77",
    curseName: "Rebranding",
    curseKey: "8718",
    controlKey: "20336",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1505",
    department: "Mercadotecnia",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "26",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "78",
    curseName: "Tropicalización de los hábitos de consumo, sectores de recuperación en la nueva normalidad",
    curseKey: "8719",
    controlKey: "20337",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1505",
    department: "Mercadotecnia",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "23",
    curseCredits: "1",
    curseStart: "7/13/20",
    curseEnd: "7/17/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "79",
    curseName: "Actualización en tópicos de calidad industrial y empresarial",
    curseKey: "8720",
    controlKey: "20338",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "5",
    curseCredits: "1",
    curseStart: "7/6/20",
    curseEnd: "7/10/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "80",
    curseName: "Como detectar mentiras en el proceso de selección de recursos humanos",
    curseKey: "8721",
    controlKey: "20339",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "9",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "81",
    curseName: "Fundamentos básicos de sueldos y salarios",
    curseKey: "8722",
    controlKey: "20340",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "9",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "82",
    curseName: "LMA: Lean Maturity Assessment como instrumento de productividad de clase mundial",
    curseKey: "8723",
    controlKey: "20341",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "11",
    curseCredits: "2",
    curseStart: "7/13/20",
    curseEnd: "7/17/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "83",
    curseName: "Los recursos humanos y el nuevo sistema judicial laboral",
    curseKey: "8724",
    controlKey: "20342",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "17",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "84",
    curseName: "Maestría personal: El nuevo perfil en los recursos humanos",
    curseKey: "8725",
    controlKey: "20343",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "10",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "85",
    curseName: "Proceso de mejora continua en organizaciones de servicio",
    curseKey: "8726",
    controlKey: "20344",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "13",
    curseCredits: "5",
    curseStart: "7/6/20",
    curseEnd: "8/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "86",
    curseName: "Repensando el género",
    curseKey: "8727",
    controlKey: "20345",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "10",
    curseCredits: "3",
    curseStart: "7/13/20",
    curseEnd: "7/17/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "87",
    curseName: "Técnicas de interpretación del lenguaje corporal",
    curseKey: "8728",
    controlKey: "20346",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1506",
    department: "Recursos Humanos",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "16",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/24/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "88",
    curseName: "Identidad con sentido en las organizaciones",
    curseKey: "8729",
    controlKey: "20347",
    centerKey: "15",
    center: "C de C Económicas y A",
    departmentKey: "1507",
    department: "Turismo",
    receptionDate: "7/8/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "7",
    curseCredits: "1",
    curseStart: "7/13/20",
    curseEnd: "7/17/20",
    autorization: "7/24/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "89",
    curseName: "Uso de Wordpress para creación de páginas web y blogs para materias prácticas de comunicación",
    curseKey: "8730",
    controlKey: "20348",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1601",
    department: "Comunicación",
    receptionDate: "7/5/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "11",
    curseCredits: "1",
    curseStart: "7/5/20",
    curseEnd: "8/7/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "90",
    curseName: "Wirecast y streaming de contenido",
    curseKey: "8731",
    controlKey: "20349",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1601",
    department: "Comunicación",
    receptionDate: "7/5/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "20",
    curseCredits: "3",
    curseStart: "7/5/20",
    curseEnd: "8/7/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "91",
    curseName: "Uso del aula virtual , de la plataforma educativa institucional ámbito académico en el rol del profesor",
    curseKey: "8732",
    controlKey: "20350",
    centerKey: "17",
    center: "C. de Educación Media",
    departmentKey: "1701",
    department: "Act Artísticas y culturales",
    receptionDate: "7/2/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "35",
    curseCredits: "3",
    curseStart: "7/13/20",
    curseEnd: "7/27/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "92",
    curseName: "Diseño de experiencias de aprendizaje y elaboración de material",
    curseKey: "8733",
    controlKey: "20351",
    centerKey: "17",
    center: "C. de Educación Media",
    departmentKey: "1702",
    department: "Act Deportivas",
    receptionDate: "7/2/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "32",
    curseCredits: "6",
    curseStart: "7/6/20",
    curseEnd: "8/2/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "93",
    curseName: "Uso y manejo del aula virtual",
    curseKey: "8734",
    controlKey: "20352",
    centerKey: "17",
    center: "C. de Educación Media",
    departmentKey: "1702",
    department: "Act Deportivas",
    receptionDate: "7/2/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "32",
    curseCredits: "5",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "94",
    curseName: "Adecuación de materiales didácticos al aula virtual",
    curseKey: "8735",
    controlKey: "20353",
    centerKey: "17",
    center: "C. de Educación Media",
    departmentKey: "1704",
    department: "C Sociales, económicas e Historia",
    receptionDate: "7/2/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "52",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "95",
    curseName: "Educando conscientemente a partir de mi ser",
    curseKey: "8736",
    controlKey: "20354",
    centerKey: "17",
    center: "C. de Educación Media",
    departmentKey: "1704",
    department: "C Sociales, económicas e Historia",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "9",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "96",
    curseName: "Arte y diversidad sexual",
    curseKey: "8737",
    controlKey: "20355",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1801",
    department: "Arte y gestión cultural",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "23",
    curseCredits: "2",
    curseStart: "8/1/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "97",
    curseName: "Arte y misticismo de las culturas indígenas Raramuri y Wixárica",
    curseKey: "8738",
    controlKey: "20356",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1801",
    department: "Arte y gestión cultural",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "1",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "98",
    curseName: "Como hacer un portafolio de artista",
    curseKey: "8739",
    controlKey: "20357",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1801",
    department: "Arte y gestión cultural",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "2",
    curseCredits: "1",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "99",
    curseName: "Diseño de proyectos culturales",
    curseKey: "8740",
    controlKey: "20358",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1801",
    department: "Arte y gestión cultural",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "2",
    curseCredits: "4",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "100",
    curseName: "Iconografía esotérica",
    curseKey: "8741",
    controlKey: "20359",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1801",
    department: "Arte y gestión cultural",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "30",
    curseCredits: "2",
    curseStart: "8/1/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "101",
    curseName: "Cuento fantástico: la imaginación como herramienta subversiva",
    curseKey: "8742",
    controlKey: "20360",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "8",
    curseCredits: "2",
    curseStart: "8/3/20",
    curseEnd: "8/21/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "102",
    curseName: "Escritura creativa sobre la pandemia",
    curseKey: "8743",
    controlKey: "20361",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "1",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "8/12/20",
    teachersCapture: "8/12/20",
  },
  {
    number: "103",
    curseName: "Estrategias de escritura para evitar el plagio: la paráfrasis y la citación.",
    curseKey: "8744",
    controlKey: "20362",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "8",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "8/12/20",
    teachersCapture: "8/12/20",
  },
  {
    number: "104",
    curseName: "Guerra civil española y la posguerra en la literatura",
    curseKey: "8745",
    controlKey: "20363",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "8",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "105",
    curseName: "Redacción científica: la escritura de la investigación.",
    curseKey: "8746",
    controlKey: "20364",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "5",
    curseCredits: "2",
    curseStart: "8/3/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "106",
    curseName: "Redacción de textos académicos científicos",
    curseKey: "8747",
    controlKey: "20365",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "8",
    curseCredits: "1",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "107",
    curseName: "Redacción en el Área Administrativa",
    curseKey: "8748",
    controlKey: "20366",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "14",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "108",
    curseName: "Redacción: ortografía",
    curseKey: "8749",
    controlKey: "20367",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "9",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "8/17/20",
    teachersCapture: "8/17/20",
  },
  {
    number: "109",
    curseName: "Taller de redacción para profesores",
    curseKey: "8750",
    controlKey: "20368",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1802",
    department: "Letras",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "5",
    curseCredits: "1",
    curseStart: "8/17/20",
    curseEnd: "8/21/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "110",
    curseName: "Diseño, redacción y evaluación de proyectos culturales",
    curseKey: "8751",
    controlKey: "20369",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1803",
    department: "Música",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "3",
    curseCredits: "2",
    curseStart: "8/10/20",
    curseEnd: "8/21/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "111",
    curseName: "Herramientas de transmisión en línea",
    curseKey: "8752",
    controlKey: "20370",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1803",
    department: "Música",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "1",
    curseStart: "7/20/20",
    curseEnd: "7/24/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "112",
    curseName: "Taller de producción radiofónica desde casa: Ventana al sonido.",
    curseKey: "8753",
    controlKey: "20371",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1803",
    department: "Música",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "15",
    curseCredits: "3",
    curseStart: "7/6/20",
    curseEnd: "7/17/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "113",
    curseName: "Procesos, Producción audiovisual y montajes",
    curseKey: "8754",
    controlKey: "20372",
    centerKey: "18",
    center: "C del Arte y de la Cultura",
    departmentKey: "1805",
    department: "Artes Escénicas y A",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "20",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "8/23/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "114",
    curseName: "Procesos básicos de taller",
    curseKey: "8755",
    controlKey: "20373",
    centerKey: "19",
    center: "C de la Ingeniería",
    departmentKey: "1902",
    department: "Ing. Automotríz",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "16",
    curseCredits: "4",
    curseStart: "7/13/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "115",
    curseName: "Diseño de técnicas de control para sistemas neumáticos, hidráulicos y eléctricos",
    curseKey: "8756",
    controlKey: "20374",
    centerKey: "19",
    center: "C de la Ingeniería",
    departmentKey: "1903",
    department: "Ing. Robótica ",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "14",
    curseCredits: "4",
    curseStart: "8/3/20",
    curseEnd: "8/21/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "116",
    curseName: "Herramientas de diseño en Ingeniería (autocad)",
    curseKey: "8757",
    controlKey: "20375",
    centerKey: "19",
    center: "C de la Ingeniería",
    departmentKey: "1903",
    department: "Ing. Robótica ",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "21",
    curseCredits: "2",
    curseStart: "8/3/20",
    curseEnd: "8/22/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "117",
    curseName: "Metodologías de evaluación en los aprendizajes orientados a proyectos de ingeniería",
    curseKey: "8758",
    controlKey: "20376",
    centerKey: "19",
    center: "C de la Ingeniería",
    departmentKey: "1903",
    department: "Ing. Robótica ",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "21",
    curseCredits: "2",
    curseStart: "7/6/20",
    curseEnd: "8/2/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "118",
    curseName: "Excel para docentes",
    curseKey: "8759",
    controlKey: "20377",
    centerKey: "20",
    center: "C Empresariales",
    departmentKey: "2002",
    department: "Agronegocios",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "15",
    curseCredits: "10",
    curseStart: "7/6/20",
    curseEnd: "7/31/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "8/12/20",
    teachersCapture: "8/12/20",
  },
  {
    number: "119",
    curseName: "Metodología para la publicación de artículos científicos",
    curseKey: "8760",
    controlKey: "20378",
    centerKey: "20",
    center: "C Empresariales",
    departmentKey: "2002",
    department: "Agronegocios",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "15",
    curseCredits: "4",
    curseStart: "8/3/20",
    curseEnd: "8/21/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "120",
    curseName: "Análisis de datos con MS Excel en Comercio electrónico",
    curseKey: "8761",
    controlKey: "20379",
    centerKey: "20",
    center: "C Empresariales",
    departmentKey: "2003",
    department: "Comercio electrónico",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "6",
    curseStart: "7/6/20",
    curseEnd: "8/14/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "121",
    curseName: "Manejo de herramientas tecnológicas en el aula y en clases en línea en Comercio Electrónico",
    curseKey: "8762",
    controlKey: "20380",
    centerKey: "20",
    center: "C Empresariales",
    departmentKey: "2003",
    department: "Comercio electrónico",
    receptionDate: "7/6/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "1",
    curseStart: "8/3/20",
    curseEnd: "8/17/20",
    autorization: "7/27/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "122",
    curseName: "Bioinformática básica",
    curseKey: "8764",
    controlKey: "20394",
    centerKey: "12",
    center: "C Básicas",
    departmentKey: "1206",
    department: "Microbiología",
    receptionDate: "7/30/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "21",
    curseCredits: "3",
    curseStart: "8/3/20",
    curseEnd: "8/23/20",
    autorization: "8/6/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "123",
    curseName: "Pasos básicos para la conformación de evidencias de aprendizaje a través de diferentes estrategias y tecnologías",
    curseKey: "N/A",
    controlKey: "N/A",
    centerKey: "6",
    center: "D. Gral. De Docencia de Pregrado",
    departmentKey: "-",
    department: "Innovación Educativa",
    receptionDate: "8/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "2",
    curseCredits: "1",
    curseStart: "-",
    curseEnd: "-",
    autorization: "8/7/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "124",
    curseName: "Creando mi primer espacio en aula virtual",
    curseKey: "-",
    controlKey: "-",
    centerKey: "6",
    center: "D. Gral. De Docencia de Pregrado",
    departmentKey: "-",
    department: "Innovación Educativa",
    receptionDate: "8/7/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "4",
    curseCredits: "2",
    curseStart: "-",
    curseEnd: "-",
    autorization: "8/7/20",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "125",
    curseName: "Enseñanza del feminismo y perspectiva de género en la educación universitaria",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1602",
    department: "Derecho",
    receptionDate: "8/13/20",
    request: "Si",
    participants: "Si",
    participantsNumber: "16",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "126",
    curseName: "Enseñanza del compilance legal de la empresa",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1602",
    department: "Derecho",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "19",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "127",
    curseName: "Técnicas en el nuevo sistema de justicia laboral",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1602",
    department: "Derecho",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "20",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "128",
    curseName: "Actualización de programas con perspectiva de género",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1604",
    department: "Filosofía",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "129",
    curseName: "Actualidad de la filosofía de la ciencia",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1604",
    department: "Filosofía",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "18",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "130",
    curseName: "Reflexiones filosófico-éticas sobre las implicaciones sociales de la pandemia Covid-19",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1604",
    department: "Filosofía",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "14",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "131",
    curseName: "Emociones, sentimientos y afectos.    Miradas desde los estudios socioculturales",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1605",
    department: "Historia",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "132",
    curseName: "Cosmovisión prehispánica mesoamericana",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1605",
    department: "Historia",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "133",
    curseName: "Primeros auxilios Psicológicos para profesores",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1608",
    department: "Psicología",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "15",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "134",
    curseName: "Métodos cuantitativos en ciencias sociales",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1608",
    department: "Psicología",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "9",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "135",
    curseName: "Métodos cualitativos en ciencias sociales",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1608",
    department: "Psicología",
    receptionDate: "8/13/20",
    request: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "136",
    curseName: "Dinámica de grupos",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1608",
    department: "Psicología",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "12",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "137",
    curseName: "Afrontamiento al estrés",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1608",
    department: "Psicología",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "16",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "138",
    curseName: "La enseñanza universitaria en tiempos de emergencia sanitaria",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1609",
    department: "Sociología",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "8",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "139",
    curseName: "Intervención breve en adicciones desde el Trabajo Social",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1610",
    department: "Trabajo Social",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "5",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "140",
    curseName: "Estrategias para disminuir el estrés por la Covid-19",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1610",
    department: "Trabajo Social",
    receptionDate: "8/13/20",
    request: "Si",
    participants: "Si",
    participantsNumber: "5",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "141",
    curseName: "Trabajo Social ante diversos escenarios del servicio público",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1610",
    department: "Trabajo Social",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "5",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "142",
    curseName: "Ideación suicida, herramientas de detección dentro del aula",
    curseKey: "-",
    controlKey: "-",
    centerKey: "16",
    center: "C Sociales y humanidades",
    departmentKey: "1610",
    department: "Trabajo Social",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "Si",
    participants: "Si",
    participantsNumber: "6",
    curseCredits: "-",
    curseStart: "-",
    curseEnd: "-",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
  {
    number: "143",
    curseName: "Fisiología Clínica de la Visión II",
    curseKey: "-",
    controlKey: "-",
    centerKey: "13",
    center: "C de la Salud",
    departmentKey: "1305",
    department: "Optometría",
    receptionDate: "8/13/20",
    request: "Si",
    cursePlan: "No",
    participants: "No",
    curseCredits: "1",
    curseStart: "12/14/20",
    curseEnd: "12/18/20",
    autorization: "-",
    responId: "-",
    comprobation: "-",
    teachersCapture: "-",
  },
];
acreditationCurses();

function acreditationCurses(filtered = [], flag) {
  if (!flag) {
    flag = false;
  }
  if (filtered.length !== 0 && !flag) {
    createTable(filtered, "filtered");
    return;
  } else {
    if (flag) {
      return;
    }
  }
  createTable(curseInformation, "center");
}

function sortCourses(courses) {
  courses = courses.sort(function (a, b) {
    if (parseInt(a.number) > parseInt(b.number)) {
      return 1;
    }
    if (parseInt(a.number) < parseInt(b.number)) {
      return -1;
    }

    return 0;
  });
}

function createTable(courses, type) {
  cleanCursesTable();
  for (let i = 0; i < courses.length; i++) {
    if (typeof courses[i] == "undefined") {
      continue;
    }
    sortCourses(courses);
    console.log(courses[i].center);
    if (
      curseselected !== "" &&
      courses[i].center !== curseselected &&
      type === "center"
    ) {
      continue;
    }
    createRow(courses[i]);
  }
}

function createRow(curseInformation) {
  const row = document.createElement("tr");
  row.innerHTML = `
        <td class="number">${curseInformation.number}</td>
        <td class="year">2020</td>
        <td class="curseName">${curseInformation.curseName}</td>
        <td class="curseKey">${curseInformation.curseKey}</td>
        <td class="controlKey">${curseInformation.controlKey}</td>
        <td class="centerKey">${curseInformation.centerKey}</td>
        <td class="center">${curseInformation.center}</td>
        <td class="departmentKey">${curseInformation.departmentKey}</td>
        <td class="department">${curseInformation.department}</td>
        <td class="receptionDate">${curseInformation.receptionDate}</td>
        <td class="request">${curseInformation.request}</td>
        <td class="cursePlan">${curseInformation.cursePlan}</td>
        <td class="participants">${curseInformation.participants}</td>
        <td class="participantsNumber">${curseInformation.participantsNumber}</td>
        <td class="curseCredits">${curseInformation.curseCredits}</td>
        <td class="curseStart">${curseInformation.curseStart}</td>
        <td class="curseEnd">${curseInformation.curseEnd}</td>
        <td class="autorization">${curseInformation.autorization}</td>
        <td class="responId">${curseInformation.responId}</td>
        <td class="comprobation">${curseInformation.comprobation}</td>
        <td class="teachersCapture">${curseInformation.teachersCapture}</td>
    `;
  acreditationList.appendChild(row);
}

function filterKey(key) {
  let found = [];
  let not_res = document.querySelector(".not-res");
  not_res.classList.add("not-shown");
  if (key.length >= 1) {
    for (let i = 0; i < curseInformation.length; i++) {
      if (typeof curseInformation[i] == "undefined") {
        continue;
      }
      if (curseInformation[i].curseKey.includes(key)) {
        found.push(curseInformation[i]);
      }
    }
    if (found.length === 0) {
      let not_res = document.querySelector(".not-res");
      not_res.classList.remove("not-shown");
      acreditationCurses(found, true);
    } else {
      acreditationCurses(found, false);
    }
  } else {
    if (key === "") {
      acreditationCurses();
    }
  }
}

function cleanCursesTable() {
  while (acreditationList.firstChild) {
    acreditationList.removeChild(acreditationList.firstChild);
  }
}

function setScrollHeight() {
  $(window).scroll(function () {
    let initTopPosition = $('.table-wrap').offset().top;
    if ($(window).scrollTop() > initTopPosition)
      $('.scrollTop').css({
        'position': 'fixed',
        'top': '0px'
      });
    else
      $('.scrollTop').css({
        'position': 'absolute',
        'top': (initTopPosition - 20) + 'px'
      });
  });
}