const acreditationList = document.querySelector("#acreditation-table tbody");


let centers = {
    agro: "C. Agropecuarias",
    basic: "C. Básicas",
    salud: "C. de la Salud",
    constr: "C. del Diseño y Construcción",
    econom: "C. Economicas y Administrativas",
    hum: "C. Sociales y Humanitarias",
    media: "Educación Media",
    artes: "Artes y la Cultura",
    ing: "C. de la Ingeniería ",
    empre: "C. Empresariales"

}
let curseInformation = [{
        center: centers["constr"],
        department: "Diseño de interiores",
        curseName: "Escalas del diseño interior",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "Si",
        curseCredits: "3",
        act: "Si",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["constr"],
        department: "Diseño de interiores",
        curseName: "Construcción de terminología metodológica del diseño interior",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "Si",
        curseCredits: "3",
        act: "Si",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["hum"],
        department: "Comunicación",
        curseName: "WireCast y streaming de contenido",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "Si",
        curseCredits: "3",
        act: "Si",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["ing"],
        department: "Ingenieria Robotica",
        curseName: "Diseño de Técnicas de Control para Sistemas Neumáticos, Hidráulicos y Eléctricos",
        request: "Si",
        cursePlan: "No",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["econom"],
        department: "Economía",
        curseName: "Herramientas Educativas Digitales \"Microsoft Teams\"",
        request: "Si",
        cursePlan: "No",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["econom"],
        department: "Economía",
        curseName: "Herramientas Educativas Digitales \"Aula Virtual UAA\"",
        request: "Si",
        cursePlan: "No",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["econom"],
        department: "Economía",
        curseName: "Herramientas Educativas Digitales \"Apps educativas para el contexto digital\"",
        request: "Si",
        cursePlan: "No",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["econom"],
        department: "Economía",
        curseName: "Uso de Series Desestacionalizados para el Análisis Económico",
        request: "Si",
        cursePlan: "No",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["artes"],
        department: "Música",
        curseName: "Taller de producción radiofónica desde casa: Ventana al Sonido",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["media"],
        department: "Actividades Artísticas y Culturales",
        curseName: "Uso de Aula Virtual de la Plataforma Educativa Institucional Ámbito Académico en el Rol de Profesor",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["basic"],
        department: "C. de la Computación",
        curseName: "Lenguaje de Java",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["basic"],
        department: "C. de la Computación",
        curseName: "Uso de las TICs para Administración de un LMS",
        request: "",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["ing"],
        department: "Ingeniería Automotriz",
        curseName: "Procesos Básicos de Taller",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["hum"],
        department: "Comunicación",
        curseName: "Uso de WordPress para Creación de Páginas Web y Blogs Para Materias Prácticas de Comunicación",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["media"],
        department: "Actividades Deportivas",
        curseName: "Capacitación para el Uso y Manejo del Aula Virtual",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["basic"],
        department: "Estadística",
        curseName: "Herramientas Digitales para la Educación Virtual",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    },
    {
        center: centers["basic"],
        department: "Estadística",
        curseName: "Herramientas Digitales en la Enseñanza de Probabilidad y Estadística",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Microbiología",
        curseName: "Herramientas Tecnológicas Básicas Orientadas a la Educación",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Fisiología y Farmacología",
        curseName: "Bioestadística Básica y Uso del programa Graph Pad Prism",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Fisiología y Farmacología",
        curseName: "Herramientas Tecnológicas en la Docencia Universtiaria",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["salud"],
        department: "Optometría",
        curseName: "Diseño Instruccional para las Asignaturas de la Licenciatura de Optometria",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["salud"],
        department: "Optometría",
        curseName: "Fisiología Clínica de la visión I",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["salud"],
        department: "Optometría",
        curseName: "Canalización de Pacientes",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Estadística",
        curseName: "Didáctica de la Estadística Básica",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Estadística",
        curseName: "Software Estadístico R como Apoyo a la Docencia",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Sistemas de la Información",
        curseName: "Introducción al Lenguaje de Programación Python",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Sistemas de Información",
        curseName: "Programación Web Básicas",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Sistemas de Información",
        curseName: "Excel Avanzado",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["ing"],
        department: "Ingeniería Robótica",
        curseName: "Herramientas de Diseño en Ingeniería (AUTOCAD)",
        request: "sI",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "no",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["ing"],
        department: "Ingeniería Robótica",
        curseName: "Metodologías de Evaluación en los Aprendizajes Orientados a Proyectos de Ingeniería",
        request: "Si",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Fisiología y Farmacología",
        curseName: "Farmacología de los Antibióticos",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Ingeniería Bioquímica",
        curseName: "Proceso de Producción, Extracción, y Purificación de Aceite de la Cannabis",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Ingeniería Bioquímica",
        curseName: "Uso de Hongos en Biorremediación",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["basic"],
        department: "Ingeniería Bioquímica",
        curseName: "Herramientas para Aula Virtual y MS Teams en Ciencias Básicas y Ingenierías ",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers["econom"],
        department: "Administración",
        curseName: "Coaching para Docentes",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }, {
        center: centers[""],
        department: "",
        curseName: "",
        request: "No",
        cursePlan: "Si",
        participants: "Si",
        curseAutorization: "No",
        curseCredits: "-",
        act: "No",
        requestoToControl: "No",
        certificatoToDSCD: "No",
        certificateDevolution: "No",
        recordsGeneration: "No",
        recordsDelivered: "No",
    }
]
acreditationCurses()

function acreditationCurses() {
    console.log(curseInformation)


    for (let i = 0; i < curseInformation.length; i++) {
        const row = document.createElement('tr');
        row.innerHTML =
            `
        <td class="center">${curseInformation[i].center}</td>
        <td class="department">${curseInformation[i].department}</td>
        <td class="curseName">${curseInformation[i].curseName}</td>
        <td class="request">${curseInformation[i].request}</td>
        <td class="cursePlan">${curseInformation[i].cursePlan}</td>
        <td class="participants">${curseInformation[i].participants}</td>
        <td class="curseAutorization">${curseInformation[i].curseAutorization}</td>
        <td class="curseCredits">${curseInformation[i].curseCredits}</td>
        <td class="act">${curseInformation[i].act}</td>
        <td class="requestoToControl">${curseInformation[i].requestoToControl}</td>
        <td class="certificatoToDSCD">${curseInformation[i].certificatoToDSCD}</td>
        <td class="certificateDevolution">${curseInformation[i].certificateDevolution}</td>
        <td class="recordsGeneration">${curseInformation[i].recordsGeneration}</td>
        <td class="recordsDelivered">${curseInformation[i].recordsDelivered}</td>
    `;
        acreditationList.appendChild(row)
    }
}